# Generated by Django 4.2.20 on 2025-03-27 12:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(1, '退货'), (2, '换货')], verbose_name='类型')),
                ('reason', models.TextField(verbose_name='原因')),
                ('status', models.IntegerField(choices=[(0, '待审核'), (1, '已同意'), (2, '已拒绝'), (3, '已完成'), (4, '已取消')], default=0, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returns', to='orders.order', verbose_name='订单')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returns', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '退换货申请',
                'verbose_name_plural': '退换货申请',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReturnImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='returns/%Y/%m/%d/', verbose_name='图片')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('return_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='returns.returnrequest', verbose_name='退换货申请')),
            ],
            options={
                'verbose_name': '退换货图片',
                'verbose_name_plural': '退换货图片',
                'ordering': ['-created_at'],
            },
        ),
    ]
