# Generated by Django 4.2.20 on 2025-03-29 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_category_options_alter_product_options_and_more'),
        ('orders', '0004_order_coupon_order_discount_amount_and_more'),
        ('returns', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnrequest',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='products.product', verbose_name='商品'),
        ),
        migrations.AlterUniqueTogether(
            name='returnrequest',
            unique_together={('order', 'product')},
        ),
    ]
