# Generated by Django 4.2.20 on 2025-03-29 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('returns', '0002_returnrequest_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnrequest',
            name='description',
            field=models.TextField(blank=True, verbose_name='问题描述'),
        ),
    ]
