# Generated by Django 4.2.20 on 2025-03-29 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('returns', '0003_returnrequest_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnrequest',
            name='quantity',
            field=models.IntegerField(default=1, verbose_name='退货数量'),
        ),
    ]
