# Generated by Django 4.2.20 on 2025-03-29 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('returns', '0004_returnrequest_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnrequest',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='退货总价'),
        ),
    ]
