# Generated by Django 4.2.20 on 2025-03-29 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_coupon_order_discount_amount_and_more'),
        ('returns', '0005_returnrequest_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnrequest',
            name='exchange_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exchange_returns', to='orders.order', verbose_name='换货订单'),
        ),
    ]
