# Generated by Django 4.2.20 on 2025-03-29 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('returns', '0006_returnrequest_exchange_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnrequest',
            name='actual_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='实际金额'),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='优惠金额'),
        ),
    ]
