# Generated by Django 4.2.20 on 2025-03-27 10:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('users', '0003_remove_user_address_alter_user_phone_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(max_length=50, unique=True, verbose_name='订单编号')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='订单总金额')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='优惠金额')),
                ('status', models.IntegerField(choices=[(0, '待付款'), (1, '待发货'), (2, '待收货'), (3, '已完成'), (4, '已取消')], default=0, verbose_name='订单状态')),
                ('shipping_name', models.CharField(max_length=50, verbose_name='收货人姓名')),
                ('shipping_phone', models.CharField(max_length=20, verbose_name='收货人电话')),
                ('shipping_province', models.CharField(max_length=50, verbose_name='省份')),
                ('shipping_city', models.CharField(max_length=50, verbose_name='城市')),
                ('shipping_district', models.CharField(max_length=50, verbose_name='区县')),
                ('shipping_address_detail', models.TextField(verbose_name='详细地址')),
                ('shipping_no', models.CharField(blank=True, max_length=50, null=True, verbose_name='物流单号')),
                ('shipping_company', models.CharField(blank=True, max_length=50, null=True, verbose_name='物流公司')),
                ('payment_method', models.CharField(blank=True, choices=[('alipay', '支付宝'), ('wechat', '微信支付'), ('bank', '银行卡')], max_length=20, null=True, verbose_name='支付方式')),
                ('payment_no', models.CharField(blank=True, max_length=50, null=True, verbose_name='支付流水号')),
                ('payment_time', models.DateTimeField(blank=True, null=True, verbose_name='支付时间')),
                ('shipping_time', models.DateTimeField(blank=True, null=True, verbose_name='发货时间')),
                ('complete_time', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('shipping_address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.useraddress', verbose_name='收货地址')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '订单',
                'verbose_name_plural': '订单',
                'db_table': 'orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100, verbose_name='商品名称')),
                ('product_image', models.CharField(max_length=255, verbose_name='商品图片')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='商品单价')),
                ('quantity', models.IntegerField(verbose_name='购买数量')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='商品总价')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='订单')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.product', verbose_name='商品')),
            ],
            options={
                'verbose_name': '订单商品',
                'verbose_name_plural': '订单商品',
                'db_table': 'order_items',
            },
        ),
    ]
