# Generated by Django 4.2.20 on 2025-03-27 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='complete_time',
        ),
        migrations.RemoveField(
            model_name='order',
            name='discount_amount',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment_no',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment_time',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_company',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_time',
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('alipay', '支付宝')], default='alipay', max_length=20, verbose_name='支付方式'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(0, '待付款'), (1, '待发货'), (2, '已完成')], default=0, verbose_name='订单状态'),
        ),
        migrations.AlterModelTable(
            name='order',
            table=None,
        ),
    ]
