# Generated by Django 4.2.20 on 2025-03-27 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_order_complete_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(0, '待付款'), (1, '待发货'), (2, '待收货'), (3, '已完成'), (4, '已取消')], default=0, verbose_name='订单状态'),
        ),
    ]
