# Generated by Django 4.2.20 on 2025-03-27 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coupon',
            options={'ordering': ['-created_at'], 'verbose_name': '优惠券', 'verbose_name_plural': '优惠券'},
        ),
        migrations.AlterModelOptions(
            name='usercoupon',
            options={'ordering': ['-created_at'], 'verbose_name': '用户优惠券', 'verbose_name_plural': '用户优惠券'},
        ),
        migrations.AlterField(
            model_name='coupon',
            name='name',
            field=models.CharField(max_length=100, verbose_name='优惠券名称'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='type',
            field=models.IntegerField(choices=[(1, '满减券'), (2, '折扣券')], verbose_name='优惠券类型'),
        ),
        migrations.AlterField(
            model_name='usercoupon',
            name='coupon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coupons.coupon', verbose_name='优惠券'),
        ),
    ]
