# Generated by Django 4.2.20 on 2025-03-27 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimage',
            options={'ordering': ['-is_main'], 'verbose_name': '商品图片', 'verbose_name_plural': '商品图片'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='product',
            name='review_count',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='order',
        ),
        migrations.DeleteModel(
            name='ProductReview',
        ),
    ]
